### ISSUE TITLE
Problem getting predicted values from GAM model

### ISSUE THREAD

**Issue by alexblickenstaff** [dbdahl/rscala#10]
I'm trying to build a GAM model in R and then use it to predict a list of input points from Scala. Here is the Scala code:

```
val xs = List(1.0, 2.0, 3.0, 4.0, 5.0)
val ys = List(1.0, 2.0, 3.0, 4.0, 5.0)
val predictXs = List(2.0, 2.5, 3.0)

val R: RClient = RClient()
R.xs = xs.toArray
R.ys = ys.toArray
R.eval("require(mgcv)")
R.eval("model = gam(ys ~ xs)")
val formattedPredictXs = predictXs.mkString("c(", ",", ")")
val res = R.evalD1(s"""predict(model, data.frame(xs = ${formattedPredictXs}))""")
println("Resulting predictions:")
res.foreach(println)
```

When run, I get this error (which is happening on the `val res = R.evalD1(s"""predict(model, data.frame(xs = ${formattedPredictXs}))""")` line):

```
Loading required package: mgcv
Loading required package: nlme
This is mgcv 1.8-24. For overview type 'help("mgcv-package")'.
Exception in thread "main" java.lang.RuntimeException: Unsupported data type.
	at org.ddahl.rscala.RClient.getInternal(RClient.scala:581)
	at org.ddahl.rscala.RClient.eval(RClient.scala:140)
	at org.ddahl.rscala.RClient.evalD1(RClient.scala:169)
```

If I change the model from `gam` to `lm` though, everything works perfectly (note the only difference is the `R.eval("model = lm(ys ~ xs)")` line):

```
val xs = List(1.0, 2.0, 3.0, 4.0, 5.0)
val ys = List(1.0, 2.0, 3.0, 4.0, 5.0)
val predictXs = List(2.0, 2.5, 3.0)

val R: RClient = RClient()
R.xs = xs.toArray
R.ys = ys.toArray
R.eval("require(mgcv)")
R.eval("model = lm(ys ~ xs)")
val formattedPredictXs = predictXs.mkString("c(", ",", ")")
val res = R.evalD1(s"""predict(model, data.frame(xs = ${formattedPredictXs}))""")
println("Resulting predictions:")
res.foreach(println)
```

That gives the output:

```
Loading required package: mgcv
Loading required package: nlme
This is mgcv 1.8-24. For overview type 'help("mgcv-package")'.
Resulting predictions:
2.0000000000000004
2.5000000000000004
3.0000000000000004
```

So for some reason the output of the `lm` prediction can be converted to a Scala object, while the output of the `gam` prediction cannot. If I print the predicted list in R using this code:

```
R.eval(s"""print(predict(model, data.frame(xs = ${formattedPredictXs})))""")
```

I get the exact same output for both the `lm` and the `gam` prediction:

```
  1   2   3 
2.0 2.5 3.0
```

I can't figure out why the `lm` results can be converted, but the `gam` results cannot -- especially given that, when printed in R, they appear to be the exact same.

**Comment by dbdahl** [comment]
The `evalD1` method is expecting a numeric vector in R, so (in your case) you need to wrap the R expression in `as.vector`, like this:

`val res = R.evalD1(s"""as.vector(predict(model, data.frame(xs = ${formattedPredictXs})))""")`

By the way, what R displays on the console may not reveal the underlying data structure.  For this, I use functions like: `str`, `is.vector`, `is.numeric`, `is.matrix`, etc.

**Comment by alexblickenstaff** [comment]
Makes sense, thank you! That fixed my issue.
