### ISSUE TITLE
eval script stop in the middle if error accured 

### ISSUE THREAD

**Issue by igreenfield** [dbdahl/rscala#11]
If in the evaluated script I get an error it stops immediately and not run to the end of the script
How can I avoid that and run to the end?

**Comment by dbdahl** [comment]
I assume you are talking about running R code from Scala.

Continuing after an error is not R's typical behavior (e.g., it does not seem to be supported by 'R CMD BATCH ...' nor R's "source" function.)

But, in these cases or in the case of running R code from Scala, you could wrap the code that may get an error in the 'tryCatch' function.
