### ISSUE TITLE
Empty array

### ISSUE THREAD

**Issue by RichardRedding** [dbdahl/rscala#12]
When passing results between R and java the output type is sometimes difficult to predict. In particular, the following returns an rscala reference when I would expect an empty matrix.

`s * 'Array.fill[Array[String]](0)(Array.fill[String](0)(""))'`

**Comment by dbdahl** [comment]
Thanks for the feedback.  The current behavior is a result of incompatibilities between R and Scala's type systems.  I'm open the suggestions, but there are some subtleties.  Consider the following code:

```R
s + '
  val a = Array.fill[Array[String]](0)(Array.fill[String](3)(""))
  val b = Array.fill[Array[String]](0)(Array.fill[String](0)(""))
'
```

Judging by your comment, it seems you would expect that `s * 'a'` would return a 0-by-3 matrix to R and that `s * 'b'` would return a 0-by-0 matrix to R.  But, in fact, to the JVM both `a` and `b` are length-zero arrays of type `Array[Array[Double]]`.  There is no "number of columns" attributes to the Scala type 'Array[Array[Double]]'.
