### ISSUE TITLE
Not able to add extra command arguments to scala call

### ISSUE THREAD

**Issue by raggaraluz** [dbdahl/rscala#14]
I don't find a way to add extra command line arguments to scala call. It can be useful to add an agentlib for debugging, or any other scala or java argument.
The only command line argument available right now is the maximum heap memory.

**Comment by raggaraluz** [comment]
Created pull request #13 addressing this issue

**Comment by dbdahl** [comment]
Accepted pull request #13 (with a few minor changes).  Thanks @raggaraluz for the contribution.
