### ISSUE TITLE
Rscala RClient() hangs (macOS)

### ISSUE THREAD

**Issue by pedrevans** [dbdahl/rscala#16]
Thanks for this very interesting package.

I am trying to get `RClient()` working, i.e. calling R from Scala.

The function RClient always hangs and never returns. In the code below, "Hello World!" is printed, but not "Goodbye!".

```
object HelloWorldRscala {

  import org.ddahl.rscala._
  def main(argv: Array[String]): Unit = {
    println("Hello World!")
    val R = RClient()
    println("Goodbye!")
  }
}
```
I've tried it with `sbt run`, and also by creating a fat jar, same result.

I am using Java 8 on macOS 10.14.5 (Mojave).

I'd be grateful for any tips to get this working :)

**Comment by dbdahl** [comment]
Two items:

1. What version of rscala are you using?  3.2.8 has a problem with embedded R in Scala, but 3.2.9 fixes this issue.

2.  Perhaps R is not in your search path.  Try providing the full path to R (and, while you're at it, enable debugging), like this:

`val R = RClient("/path/to/R_HOME/bin/R", 0, true)`

Do either of these fix the issue?

**Comment by pedrevans** [comment]
Thanks for the feedback.

I've got 3.2.9. Using the full path didn't help:
`    val R = RClient("/usr/local/bin/R", 0, true)`

There is no debug output.

**Comment by dbdahl** [comment]
I have reproduced the error but don't yet know the cause.  I hope to release a fix soon.  In the meantime, you can use an older version (specifically, 3.2.6 or older).  That is, in your build.sbt, please use:

`libraryDependencies += "org.ddahl" %% "rscala" % "3.2.6"`

Thanks for your report and patience.

**Comment by dbdahl** [comment]
The latest release (3.2.10) addresses this issue.  Would you please test on your end and close this issue if everything looks good?  Thanks.

`libraryDependencies += "org.ddahl" %% "rscala" % "3.2.10"`

**Comment by pedrevans** [comment]
It doesn't hang anymore. Well done and thanks a lot!
