### ISSUE TITLE
What's the correct usage of RClient

### ISSUE THREAD

**Issue by bithw1** [dbdahl/rscala#2]
Hi,
We are having a web application based on Play,  when concurrent user requests comes, do the computation by calling the R code. The request should be done as fast as possible.
I noticed that creating RClient itself will cost 1.5 seconds 
`val R = org.ddahl.rscala.RClient(serializeOutput = true)`

I would ask whether I used RClient correctly:
1. When a request comes, then create a RClient, and do the job with this RClient, so if there are many requests concurrently ,there would be more than one RClient instances running, I am not familiar with internals of the RClient, so I would ask whether it is ok to use RClient in this way.

2. If above usage is OK, i would ask whether I can pool the RClient instances beforehand, so that, when a request comes, it can use a RClient from the pool. I am afraid that if the RClient in the pool has been used for a long time, then the  RClient will be outdated, eg, due to the connection timeout 

3. I notice that RClient doesn't have close method,I would ask when the resources that RClient uses will be released

**Comment by dbdahl** [comment]
Regarding each of your points:

1. Yes, each instance of the RClient class creates an independent R process and you can have as many processes as you have computing resources.

2. Sure, you could create a pool as you describe.  Regarding connection timeout, the underlying R code uses the makeSocket function with timeout=2678400, which translates to 31 days.  The R documentation says:

> timeout:  numeric: the timeout (in seconds) to be used for this connection.  Beware that some OSes may treat very large values as zero: however the POSIX standard requires values up to 31 days to be supported.

My guess is that you will want to design your pool such a stale RClient are replaced with a new one.

3. Use the exit method.  See the [Scaladoc](https://dahl.byu.edu/software/rscala/scaladoc/org/ddahl/rscala/RClient.html).

By the way, you might also consider [Rserve](https://www.rforge.net/Rserve/) and [RCaller](https://github.com/jbytecode/rcaller) for your project.

**Comment by bithw1** [comment]
Thanks @dbdahl for the helpful answer.
a). Regarding question 2, yes, if I am to use pool, I will have to take care of detecting stale RClient and replace it with new one, 

Detecting stale RClient looks non-trivial, my first thought is to schedule a task to ask RClient to run simple code like `x <- 1` every 3 minutes:
1. Keep RClient alive
2. If errors occur for this simple code, then I would think the RClient is problematic and should be replaced with new one.

With this design, there are two things to think about
1. The detection/replacement logic is done in the scheduled task.The following scenario may occur: RClient is stale between the 3 minutes window, and error will occur if the RClient does the  business logic at this point , but I can't tell whether the error is caused by RClient itself or by the code error,so that I would just fail the request and wait the task to replace this RClient if it is problematic.

> Or, I would ask whether there is information that I can use to know RClient is problematic

2.  RClient should be synchronized, since there are many thread（scheduler task thread，user request thread) may work on the RClient.

b). I will take Rserve and RCaller as well, thanks @dbdahl 





 

I will take a look at Rserve,RCaller.

**Comment by bithw1** [comment]
@dbdahl do you have some thought on how to detect stale RClient?

**Comment by dbdahl** [comment]
@bithw1 You raise some good points.

1.  Regarding a stale RClient, I just added a new method "ping" which returns a Boolean indicating whether the connection is alive.  You can use this to detect a stale RClient.  Aside from the OS killing the underlying R process, I don't know why an RClient might get stale in the first place.  Any insights are appreciated.

2.  Methods of the RClient are now synchronized such that multiple threads can simultaneously access the same RClient.

The changes are in the repository now and will be in the next officially release to CRAN in a few weeks.  In the meantime, you can access the updated JAR files here:

https://dahl.byu.edu/public/rscala-2.2.3-SNAPSHOT.tar.gz

**Comment by bithw1** [comment]
Thanks @dbdahl for helping me clarify the working of RClient, and many thanks for you for bringing such an awesome project, :-)

I will try the new features in the coming release, they are really awesome.

1. I will try and use _Ping_  for stale detection
2. With _Methods of the RClient are now synchronized_ feature , Looks I could safely call _RClient.eval_ concurrently, asking RClient to run the user R code(corresponding to the user request) in one by one manner ,it will somehow simplify my synchronization design on the RClient pool.

**Comment by bithw1** [comment]
I  am closing this issue.
