### ISSUE TITLE
ps exceptions

### ISSUE THREAD

**Issue by pedrevans** [dbdahl/rscala#20]
Hi there.

When running tests I get an exception from `ps` complaining that the `-p` option does not have an argument.

Environment:
MacOS 10.14.6 Mojave
Rscala:  "org.ddahl"   %% "rscala"   % "3.2.16",
sbt.version=1.3.3
Scala 2.13

I'm calling an R script from Scala. The call is working, but under normal circumstances I'm seeing the error `ps: option requires an argument -- p`

    scriptName = singlet_gate_fc_wrapper

    [1] 0.10000000 0.06559273 0.10000000 0.17368241 4.00000000 4.04467395 4.00000000
    [8] 3.92850483

    ps: option requires an argument -- p

    usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]

          [-g grp[,grp...]] [-u [uid,uid...]]

          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]

       ps [-L]

    Error in rbyte(socketIn) : Scala seems to have died.

If I run the test from the IntelliJ debugger I don't get this error.

Any idea what I am doing wrong?

**Comment by dbdahl** [comment]
Thanks for making a report.  I have a fix for the output related to "ps".  But, whether that is a symptom or the underlying cause of the problem, I'm not sure.  I have posted a new development version that can be installed in R as follows:

`install.packages("https://dbdahl.github.io/rpackages/src/contrib/rscala_3.2.16-20191025-0754.tar.gz",type="source",repos=NULL)`

For your usage (calling an R script from Scala),  you will need to find the "rscala.jar" file:

`system.file("java/scala-2.13/rscala.jar",package="rscala")`

Then copy it to the "lib" directory where your build.sbt resides.  An you will want to comment out the line:

`libraryDependencies += "org.ddahl" %% "rscala" % "3.2.16"`

in your build.sbt file.

Feedback in appreciated.  If this doesn't solve the problem, I will likely your help in finding a minimal working example that produces the issue.  Thanks.

**Comment by pedrevans** [comment]
Thanks a lot for the quick turnaround!

In the meantime I found the underlying problem was in my code. It wasn't the "ps". A Scala test was exiting without waiting for the reply from R. After I fixed the test the "ps" error disappeared. So I'll wait for your next regular update before updating the rscala package.

Thanks for a great package, by the way, it's opening doors for us :)

**Comment by pedrevans** [comment]
I'm afraid I must revise my previous comment. I'm still getting the ps problem, even when sending a quit before exiting. I'll give your fix a go.
