### ISSUE TITLE
Wrong artifact id on scaladex

### ISSUE THREAD

**Issue by hangyas** [dbdahl/rscala#22]
Hi

I'm not familiar deeply with scaladex or maven, so I'm not sure why, but:

https://index.scala-lang.org/dbdahl/rscala/ redirects to https://index.scala-lang.org/dbdahl/rscala/commonsmath/1.2.2?target=_2.13

And on the right side you can see stuff like
```
libraryDependencies += "org.ddahl" %% "commonsmath" % "1.2.2"
```

instead of

```
libraryDependencies += "org.ddahl" %% "rscala" % "3.2.19"
```

(which is btw correct in the readme and the body of the scaladex page)

**Comment by dbdahl** [comment]
Thanks for filing this issue.  I see the problem but cannot see how to fix it.  That is, I too am unfamiliar with scaladex, so I welcome any hints/help for anyone who might help me sort this out.  Thanks!

**Comment by dbdahl** [comment]
Seems to have fixed itself.  Thanks for the report, @hangyas.
