### ISSUE TITLE
RObject is not Serializable and has no public constructor

### ISSUE THREAD

**Issue by tmichniewski** [dbdahl/rscala#23]
Hello David @dbdahl,

We are trying to use RScala library in a Scala project and use it to call R functions. Our application is executed on Azure Databricks (so something like Apache Spark). We face cases where some data were prepared on a driver machine and we have them in some R variables in R session on a driver. But we also want to process same other data the Spark way, so compute something on workers.

Now, the computation we are trying to perform on the workers needs to use some values already computed on the driver in its R session (called from Scala via RScala). So we thought about calling a Spark User Defined Function, which would be supplied with necessary data captured from the driver (Scala closure). To achieve this we need to somehow pass the value from driver to the User Defined Function.

So basically we try to do something like this:
```scala
val s = "text"
val testFun: () => String =
  () => {
    val r = RClient()
    r.evalObject("s <- %-", s) // captue s value from outside of testFun
    r.eval("x <- modify(s)") // call some R function to work on s
    val result = r.getS0("x") // finally return computed value x
    r.quit()
    result
  }
val testUDF = udf(testFun)
```
So far so good and this works on Spark. For now let's ignore the cost of creating the RClient object and its closing (quit()).

The problem is that in majority of cases the captured value is not that simple as a string, but also might be much more complex like R list of several elements which in turn contains another lists/elements and so on.

What we tried to do was to capture not only the scalar values but the whole complex list. So we want to achieve something like this:
```scala
val s = r.evalObject("some_list") // take a complex R list as RObject
val testFun: () => String =
  () => {
    val r = RClient()
    r.evalObject("s <- %-", s) // capture s value from outside of testFun, this time as an RObject
    r.eval("x <- modify(s)") // call some R function to work on s
    val result = r.getS0("x") // finally return computed value x
    r.quit()
    result
  }
val testUDF = udf(testFun)
```

The problem with above code snippet is that Spark complains that "RObject is not Serializable" and therefore cannot be distributed to the workers. So Spark issues runtime error.

So as a remedy we thought about reading the RObject as Array[Byte] like here:
```scala
val s = r.evalObject("some_list").x // get the real bytes, Yes, the x value is public
val testFun: () => String =
  () => {
    val r = RClient()
    r.evalObject("s <- %-", new RObject(s)) // capture s value from outside of testFun, this time as Array[Byte]
    r.eval("x <- modify(s)") // call some R function to work on s
    val result = r.getS0("x") // finally return computed value x
    r.quit()
    result
  }
val testUDF = udf(testFun)
```
Unfortunatelly this does not work nor even compile, because RObject does not have public constructor.

Do you see any solution of this puzzle?
Is there any reason why RObject is not Serializable and does not have a public constructor?
I guess making RObject Serializable or making its constructor public should solve this problem.

If this cannot be amended, then we have to pass the comlpex list after having decomposed it into smaller and simpler data structures which is a time consuming process. But at the moment this seems to be the only solution, as RScala supports only scalars, Arrays and Arrays of Arrays, so rather simple data structures, but nothing more and using RObject would be a nice work around.

**Comment by dbdahl** [comment]
Thanks for the detailed issue report, @tmichniewski.  I only have passing familiarity with Apache Spark and have never used it, but I think the following example should illustrate a path forward for you.  You would need to arrange to distribute 's' (an Array[Byte]) to the workers.

```scala
val r = RClient()
r.eval("first <- list(company='IBM', value=117.70, plan=function(x) 2*x)")
val s = r.evalObject("first").x
r.eval("second <- unserialize(%-)", s)
println(r.evalL0("identical(first, second)"))
r.quit()
```

**Comment by dbdahl** [comment]
In the previous example, the line

```scala
val s = r.evalObject("first").x
```

is equivalent to

```scala
val s = r.evalR1("I(serialize(first,NULL))")
```

**Comment by tmichniewski** [comment]
Hello David @dbdahl,
Thank you, this is what I was looking for. This seems to be working on Spark. So I close this ticket.
Tomek
