### ISSUE TITLE
When the message: "Scala seems to have died" is issued?

### ISSUE THREAD

**Issue by tmichniewski** [dbdahl/rscala#25]
Hello David @dbdahl,

We observe the title message. Is it normal?
It is issued from rbyte R function which is called from pop function.

Or in other words - what is the correct scenario of closing the bridge between Scala and R? In our case we create RClient object in UDF, do the job and call quit() on RClient object, while an instant later the RClient object might get invalidated as not being in the scope of function body which ended and the GC might get it garbage collected.

So is my understanding correct that the R session still exists and only when it discovers that the RClient disappeared then this pop function ends the processing with message "Scala seems to have died"?

**Comment by tmichniewski** [comment]
After second thoughs I think that in normal situation (meaning there are no runtime errors) the R session should be closed within call to quit() method, so there would be no room for scenario where R counter part should detect that "Scala seems to have died". If so, then when this message might be issued? In our case it seems that this message is issued during normal course of events, where there are no runtime errors.

**Comment by dbdahl** [comment]
"Scala seems to have died" is issued when the TCP/IP connection between the JVM process and the R process is broken, or, at least, not behaving as the R code would expect.  Why it happens has been difficult to track down.
