### ISSUE TITLE
RScala doesn't handle encoding correctly?

### ISSUE THREAD

**Issue by bithw1** [dbdahl/rscala#5]
Hi @dbdahl ,

I encounter an interesting problem, in the following code, I am using Chinese words` 你来自哪里` to create a vector(By the way, the words mean ` where are you from` in English)

```
  val R = org.ddahl.rscala.RClient(serializeOutput = true)
    val code =
      """
          x <- c("你来自哪里")
         "done"
      """.stripMargin(' ')
    try {
      val ret = R evalS0 code
      println(ret)
    } catch {
      case e: Exception => e.printStackTrace()
    } finally {
      R.exit()
    }
  }
```

An exception occurs when running the above code, the error message is:
```
java.lang.RuntimeException: Error in R evaluation.
	at org.ddahl.rscala.RClient.eval(RClient.scala:112)
```

but if I am using ` x <- c("你来自哪")`,then  it works, the error one is using 5 characters, and the correct one is using 4 characters.

I am using UTF-8, I have no idea where the problem lies,@dbdahl ,could you please take a look?

NOTE: both cases are working with RStudio.

**Comment by zhengcanbin** [comment]
same question

**Comment by dbdahl** [comment]
@bithw1

I am not very familiar with string encodings, but I successfully ran your Scala code on my three test machines:  Ubuntu 16.04, Mac OS X , and Windows 10.  I believe that I'm using UTF-8 as well (as least, that is what is reported by the LANG environment variables on Ubuntu and Mac).

When you say that "both cases are working with RStudio", do you mean that you are editing the Scala script using RStudio's text editor?  (I don't think you can run Scala scripts from RStudio, can you?)

Can you, perhaps working with @zhengcanbin, help me know what to do to reproduce this error?  Thanks.

**Comment by bithw1** [comment]
Thanks @dbdahl for the reply. I mean to run the following R code in RStudio:
```

          x <- c("你来自哪里")
         "done"
```
and 

```
          x <- c("你来自哪")
         "done"
```

The problem looks weird,since I am busy working on the project, I will investigate this problem once I got time.As a work around, I am using English words in the project.

**Comment by bithw1** [comment]
>  help me know what to do to reproduce this error

Sorry, I have no idea how to reproduce the error in your end. maybe language, OS, locale involved

**Comment by dbdahl** [comment]
@bithw1 Please see [this commit](https://github.com/dbdahl/rscala/commit/d36473bf10562e3d3ab81c7f0185ea9a1a0fd2a3) and try with 
the updated JAR files here:

https://dahl.byu.edu/public/rscalaJars_LATEST.tar.gz

and the R package here:

https://dahl.byu.edu/public/rscala_LATEST.tar.gz

Does that resolve this issue?

If not, please see if you can patch the "wc" and "rc" functions in [R/rscala/R/scala.R](https://github.com/dbdahl/rscala/blob/master/R/rscala/R/scala.R) and/or the "writeString" and "readString" functions in [rscala/src/main/scala/org/ddahl/rscala/server/Helper.scala](https://github.com/dbdahl/rscala/blob/master/src/main/scala/org/ddahl/rscala/server/Helper.scala).

**Comment by dbdahl** [comment]
Given my successful testing of this update and the lack of response to the contrary, I am assuming this issue is resolved.  I'd be glad to re-open as needed.

**Comment by bithw1** [comment]
Sorry for the late  response, @dbdahl . I updated the rscala to the latest version (2.3.1) and rerun the code, it succeeds now , Thank you @dbdahl !
