### ISSUE TITLE
Question: do you have an example of how to include R libraries in scala code?

### ISSUE THREAD

**Issue by tomer-ben-david** [dbdahl/rscala#7]
First fascinating project!! is there an example of how to include R libraries in a scala project? thanks..

**Comment by dbdahl** [comment]
If only want to embed R in a Scala application, simply add the following line to the your SBT build.sbt file:

libraryDependencies += "org.ddahl" %% "rscala" % "2.5.0"

Then, in your Scala code, you can instantiate an R instance as described in the paper:

https://dahl.byu.edu/software/rscala/article.pdf

or as shown here:

https://dahl.byu.edu/software/rscala/scaladoc/org/ddahl/rscala/RClient.html

You will need to install R yourself in the usual manner.  You will also need to install any desired packages/libraries in the usual manner.

**Comment by tomer-ben-david** [comment]
yeah it's working, thank you for the great project, and the help.  i will try also later the other side to incorporate scala into R.  I just wonder how simple/complex that would be assuming I have a `build.sbt` with tens of dependencies..
