### ISSUE TITLE
missed "oganization" setting in build.sbt

### ISSUE THREAD

**Issue by newffy** [dbdahl/rscala#8]
Hello!
I can't find artifacts rscala in central maven repo newer than 2.5. 
It looks like you missed setting "organization" in build.sbt.

**Comment by dbdahl** [comment]
The "organization" has been added to build.bst in commit d8d8c38.

Yes, the latest release to Central Maven Repository is version 2.5.3.  Embedding R in a Scala was initially not part of the rscala 3.x rewrite, but I am now readying a release with that functionality.  I will close this issue when it is released.

Thanks.

**Comment by newffy** [comment]
So, for using R from Scala it's better to use 2.5.3 version?
I built 3.2.0 for me and it's failing with NPE inside ```org.ddahl.rscala.RClient()```

**Comment by dbdahl** [comment]
Yes, please use version 2.5.3 until a later release is available.

**Comment by vreuter** [comment]
Thank you, bumping down to `2.5.3` allowed the resolution to work for me.

**Comment by dbdahl** [comment]
Version 3.2.1 has been released.  Note the API differs somewhat from the 2.x.x series.

A paper describing the software is "conditionally accepted" and "in editing" at the Journal of Statistical Software.  The paper is available [here](https://dahl.byu.edu/public/rscala/rscala.pdf).

To access R in a Scala application, simply add the following line to the your SBT build.sbt file:

libraryDependencies += "org.ddahl" %% "rscala" % "3.2.1"
