### ISSUE TITLE
working with R lists

### ISSUE THREAD

**Issue by newffy** [dbdahl/rscala#9]
Hello!
I need to pass R list from Scala code to R and to read list back to Scala.
As I understand, I can pass list to R via chained calls of ```RClient.eval```, ```RClient.set(identifier, index, singleBrackets)```, as mentioned in comments to ```set``` method, although maybe you can suggest more efficient method.
But is there way to get list content back to Scala? It looks like R lists as full-blown type are not supported. Call to ```RClient.get("myList$names")``` fails with "Undefined identifier".  

P.S. currently I'm on 2.5.3 version

**Comment by dbdahl** [comment]
Correct, for version 2.5.3, that is the recommended way to create list in R from Scala.

As far as getting back the list content, I recommend RClient.evalS1("myList$names") which will return an array whose type is "Array[String]".
